In [30]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [8]:
X,y=make_classification(n_samples=1000, n_features=4, random_state=123)

In [9]:
X

array([[-0.68563935,  0.66166786, -0.49794848,  0.1640298 ],
       [ 0.82634696,  1.60036775, -0.79590478,  1.01692483],
       [ 1.82166323, -0.61717505,  0.65880344,  0.14206338],
       ...,
       [-1.31657018,  1.38559251, -1.0231497 ,  0.3732512 ],
       [ 1.32292314, -1.51525852,  1.09968727, -0.43734776],
       [-2.09298379, -1.87407975,  0.74703166, -1.47173036]])

In [10]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,

In [32]:
#Slpitting Dataset
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3, random_state=42)

In [33]:
X_train.shape

(700, 4)

In [34]:
X_test.shape

(300, 4)

In [35]:
model=LogisticRegression()

In [36]:
#Training the model here
model.fit(X_train,y_train)

LogisticRegression()

In [41]:
model.score(X_train,y_train)
#MY model is able to pred 94% data

0.9557142857142857

In [42]:
#Validation State
#testing data
y_pred=model.predict(X_test)

In [43]:
accuracy_score(y_test,y_pred)

0.9466666666666667

In [44]:
confusion_matrix(y_test,y_pred)

array([[140,   9],
       [  7, 144]], dtype=int64)